"""Add created_at and updated_at

Revision ID: a810d320de9a
Revises: bc664c4fa863
Create Date: 2025-08-09 20:05:35.129968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a810d320de9a'
down_revision: Union[str, Sequence[str], None] = 'bc664c4fa863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Feedback table
    op.add_column(
        'feedbacks',
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False
        )
    )
    op.add_column(
        'feedbacks',
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            nullable=True  # Changed from False to True
        )
    )

    # Users table
    op.add_column(
        'users',
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False
        )
    )
    op.add_column(
        'users',
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            nullable=True  # Changed from False to True
        )
    )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('feedbacks', 'updated_at')
    op.drop_column('feedbacks', 'created_at')
    # ### end Alembic commands ###
